Voltage <- as.vector(household_sub[["Voltage"]])
Global_reactive_power <- as.vector(household_sub[["Global_reactive_power"]])

par(mfrow=c(2,2))
plot(New_Time, a.vector, type = "l", ylab = "Global Active Power (kilowats)", xlab = "Time")
plot(New_Time, Voltage, type = "l", ylab = "Voltage", xlab = "Time")
plot(New_Time, Sub_metering_1, type = "l", xlab = "Time", ylab = "Energy sub metering")
lines(New_Time, Sub_metering_2, type = "l", col= "red")
lines(New_Time, Sub_metering_3, type = "l", col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd=2, col = c("black", "red", "blue"), cex=0.2)
plot(New_Time, Global_reactive_power, type = "l", xlab = "Time", ylab = "Global reactive power")
dev.off()